USE [master]
GO
/****** Object:  Database [Tarea6]    Script Date: 04/11/2020 15:58:00 ******/
CREATE DATABASE [Tarea6]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tarea6', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Tarea6.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Tarea6_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Tarea6_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Tarea6] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tarea6].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Tarea6] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Tarea6] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Tarea6] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Tarea6] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Tarea6] SET ARITHABORT OFF 
GO
ALTER DATABASE [Tarea6] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Tarea6] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Tarea6] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Tarea6] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Tarea6] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Tarea6] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Tarea6] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Tarea6] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Tarea6] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Tarea6] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Tarea6] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Tarea6] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Tarea6] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Tarea6] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Tarea6] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Tarea6] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Tarea6] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Tarea6] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Tarea6] SET  MULTI_USER 
GO
ALTER DATABASE [Tarea6] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Tarea6] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Tarea6] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Tarea6] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [Tarea6]
GO
/****** Object:  Table [dbo].[Estudiantes]    Script Date: 04/11/2020 15:58:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estudiantes](
	[idEstudiante] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](25) NOT NULL,
	[matri] [varchar](9) NOT NULL,
	[edad] [int] NOT NULL,
	[carrera] [nchar](30) NOT NULL,
	[pais] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Estudiantes] PRIMARY KEY CLUSTERED 
(
	[idEstudiante] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Login]    Script Date: 04/11/2020 15:58:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Login](
	[idLogin] [int] NOT NULL,
	[admin] [varchar](15) NOT NULL,
	[clave] [int] NOT NULL,
 CONSTRAINT [PK_Login] PRIMARY KEY CLUSTERED 
(
	[idLogin] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Estudiantes] ON 
GO
INSERT [dbo].[Estudiantes] ([idEstudiante], [name], [matri], [edad], [carrera], [pais]) VALUES (6, N'Huascar', N'20198773', 17, N'Mecatronica                   ', N'España')
GO
INSERT [dbo].[Estudiantes] ([idEstudiante], [name], [matri], [edad], [carrera], [pais]) VALUES (11, N'Kevin', N'20198682', 20, N'Software                      ', N'Estados Unidos')
GO
SET IDENTITY_INSERT [dbo].[Estudiantes] OFF
GO
INSERT [dbo].[Login] ([idLogin], [admin], [clave]) VALUES (1, N'Administrador', 1234)
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Estudiantes]    Script Date: 04/11/2020 15:58:01 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Estudiantes] ON [dbo].[Estudiantes]
(
	[matri] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Tarea6] SET  READ_WRITE 
GO
